/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentCard: typeof import('./src/components/agentCard/agentCard.vue')['default']
    AgentFormDialog: typeof import('./src/components/dialog/create_agent/AgentFormDialog.vue')['default']
    CommonCard: typeof import('./src/components/commonCard/commonCard.vue')['default']
    Create_agent: typeof import('./src/components/dialog/create_agent/create_agent.vue')['default']
    Drawer: typeof import('./src/components/drawer/drawer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HAvatar: typeof import('./src/components/ui/HAvatar/HAvatar.vue')['default']
    HButton: typeof import('./src/components/ui/HButton/HButton.vue')['default']
    HDialog: typeof import('./src/components/ui/HDialog/HDialog.vue')['default']
    HDrawer: typeof import('./src/components/ui/HDrawer/HDrawer.vue')['default']
    HDropdown: typeof import('./src/components/ui/HDropdown/HDropdown.vue')['default']
    HDropdownItem: typeof import('./src/components/ui/HDropdown/HDropdownItem.vue')['default']
    HForm: typeof import('./src/components/ui/HForm/HForm.vue')['default']
    HFormItem: typeof import('./src/components/ui/HForm/HFormItem.vue')['default']
    HIcon: typeof import('./src/components/ui/HIcon/HIcon.vue')['default']
    HInput: typeof import('./src/components/ui/HInput/HInput.vue')['default']
    HistortCard: typeof import('./src/components/historyCard/histortCard.vue')['default']
    HMessage: typeof import('./src/components/ui/HMessage/HMessage.vue')['default']
    HMessageBox: typeof import('./src/components/ui/HMessageBox/HMessageBox.vue')['default']
    HOption: typeof import('./src/components/ui/HSelect/HOption.vue')['default']
    HSelect: typeof import('./src/components/ui/HSelect/HSelect.vue')['default']
    HSkeleton: typeof import('./src/components/ui/HSkeleton/HSkeleton.vue')['default']
    HTable: typeof import('./src/components/ui/HTable/HTable.vue')['default']
    HTabPane: typeof import('./src/components/ui/HTabs/HTabPane.vue')['default']
    HTabs: typeof import('./src/components/ui/HTabs/HTabs.vue')['default']
    HTag: typeof import('./src/components/ui/HTag/HTag.vue')['default']
    HTooltip: typeof import('./src/components/ui/HTooltip/HTooltip.vue')['default']
    HUpload: typeof import('./src/components/ui/HUpload/HUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
