export { default as Interview } from './interview.vue'
export { default as InterviewDefault } from './defaultPage/defaultPage.vue'
export { default as InterviewChat } from './chatPage/chatPage.vue'
export { default as InterviewReport } from './reportPage/reportPage.vue'
export { default as InterviewLearning } from './learningPage/learningPage.vue'
export { default as InterviewHub } from './hubPage/hubPage.vue'
export { default as InterviewQuestionDetail } from './questionDetailPage/questionDetailPage.vue'
